services:
  - type: web
    name: py-runner-bot
    env: python
    plan: free

    runtime: python
    pythonVersion: 3.11.9   # ðŸ”¥ KRÄ°TÄ°K SATIR

    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true

    envVars:
      - key: BOT_TOKEN
        sync: false
